server:
  port: 8888
zuul:
  routes:
    course:
      path: /course/**
      url: http://course-dubbo-edge-service:8084/course/
    user:
      path: /user/**
      url: http://user-edge-service:8083/user/