server:
  port: 8084
spring:
  application:
    name: course-dubbo-edge-service
  dubbo:
    registry: zookeeper://${zookeeper.address}:2181
thrift:
  user:
    ip: user-thrift-service
    port: 8889
user:
  edge:
    service:
      url: http://user-edge-service:8083