server:
  port: 8082
spring:
  application:
    name: course-dubbo-edge-service
  dubbo:
    registry: zookeeper://localhost:2181
thrift:
  user:
    ip: localhost
    port: 7911
user:
  edge:
    service:
      url: http://localhost:8081