FROM openjdk:8-jre

MAINTAINER wangxh m13656657690@163.com

COPY target/course-dubbo-edge-service-0.0.1-SNAPSHOT.jar /course-dubbo-edge-service.jar


ENTRYPOINT ["java", "-jar", "/course-dubbo-edge-service.jar"]