service:
  name: user-thrift-service
  port: 8082
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/db_user
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd@123
