server:
  port: 8083
  name: user-edge-service
thrift:
  user:
    ip: user-thrift-service
    port: 8082
  message:
    ip: message-thrift-python-service
    port: 8081
spring:
  redis:
    host: ${redis.address}
    port: 6379
    timeout: 3000